version: '3'

services:
  django:
    container_name: arnold_django
    build: .
    entrypoint: sh ./docker-entrypoint.sh
    volumes:
      - .:/app
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - arnold_network

  nginx:
    image: nginx:latest
    container_name: arnold_nginx
    ports:
      - "8080:80"
      - "8443:43"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - django
    env_file:
      - .env
    networks:
      - arnold_network

networks:
  arnold_network:
    driver: bridge