# Generated by Django 4.0.4 on 2024-08-31 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('meal_status', models.CharField(choices=[('done', 'Done'), ('partially_done', 'Partially Done'), ('not_done', 'Not Done')], max_length=20)),
                ('feeling_status', models.CharField(blank=True, choices=[('happy', 'Happy'), ('quiet', 'Quiet'), ('normal', 'Normal'), ('sad', 'Sad'), ('anger', 'Anger'), ('anxiety', 'Anxiety')], max_length=10)),
                ('appetite_status', models.CharField(blank=True, choices=[('hunger', 'Hunger'), ('desire_to_eat', 'Desire to Eat'), ('satisfied', 'Satisfied'), ('stew', 'Stew')], max_length=15)),
                ('food_replacement', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
