# Generated by Django 4.0.4 on 2024-08-31 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        ('daily_records', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecords',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Athlete', to='user.athlete'),
        ),
        migrations.AddField(
            model_name='dailyrecords',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to='meal.meal'),
        ),
    ]
