# Generated by Django 4.0.4 on 2024-09-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0005_alter_dailyrecords_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecords',
            name='feeling_status',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('quiet', 'Quiet'), ('normal', 'Normal'), ('sad', 'Sad'), ('anger', 'Anger'), ('anxiety', 'Anxiety'), ('fear', 'Fear')], max_length=10),
        ),
    ]
