# Generated by Django 4.0.4 on 2024-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_athlete_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.CharField(choices=[('MENS_PHYSIQUE', 'Mens Physique'), ('BODYBUILDER', 'Bodybuilder'), ('CLASSIC', 'Classic'), ('WELLNESS', 'Wellness'), ('FIGURE', 'Figure'), ('FIT_MODEL', 'Fit Model'), ('NOVICE', 'Novice'), ('TRUE_NOVICE', 'True Novice'), ('OVERCOMING', 'Overcoming')], max_length=50),
        ),
    ]
