# Generated by Django 4.0.4 on 2024-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.JSONField(default=list),
        ),
    ]
