# Generated by Django 4.0.4 on 2024-08-31 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacrosSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('week', models.PositiveIntegerField(default=0)),
                ('cho', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ptn', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fat', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('kcal', models.FloatField(default=0)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros_sheets', to='diet.diet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
