# Generated by Django 4.0.4 on 2024-09-01 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
        ('macros_sheet', '0002_remove_macrossheet_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealMacrosSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macros_sheet', to='meal.meal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MacrosSheet',
        ),
    ]
