# Generated by Django 4.0.4 on 2024-09-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_initial'),
        ('meal', '0001_initial'),
        ('macros_sheet', '0004_dietmacrossheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmacrossheet',
            name='diet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_macros_sheet', to='diet.diet'),
        ),
        migrations.AlterField(
            model_name='mealmacrossheet',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_macros_sheet', to='meal.meal'),
        ),
    ]
